import type { Summary } from "@gnani/shared";

export function SummaryView({ summary, modelUsed }: { summary: Summary; modelUsed?: string | null }) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold">{summary.title}</h2>
        <p className="mt-2 text-[var(--muted)]">{summary.tldr}</p>
      </div>

      {summary.key_points.length > 0 && (
        <section>
          <h3 className="mb-2 font-medium">Key Points</h3>
          <ul className="list-inside list-disc space-y-1 text-sm">
            {summary.key_points.map((point, i) => (
              <li key={i}>{point}</li>
            ))}
          </ul>
        </section>
      )}

      {summary.action_items.length > 0 && (
        <section>
          <h3 className="mb-2 font-medium">Action Items</h3>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b text-left text-[var(--muted)]">
                <th className="pb-2 pr-4">Item</th>
                <th className="pb-2">Owner</th>
              </tr>
            </thead>
            <tbody>
              {summary.action_items.map((item, i) => (
                <tr key={i} className="border-b border-[var(--border)]">
                  <td className="py-2 pr-4">{item.text}</td>
                  <td className="py-2 text-[var(--muted)]">{item.owner ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {summary.open_questions.length > 0 && (
        <section>
          <h3 className="mb-2 font-medium">Open Questions</h3>
          <ul className="list-inside list-disc space-y-1 text-sm">
            {summary.open_questions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>
      )}

      {summary.unclear_segments.length > 0 && (
        <section>
          <h3 className="mb-2 font-medium">Unclear Segments</h3>
          <ul className="list-inside list-disc space-y-1 text-sm text-[var(--muted)]">
            {summary.unclear_segments.map((seg, i) => (
              <li key={i}>{seg}</li>
            ))}
          </ul>
        </section>
      )}

      {modelUsed && (
        <p className="text-xs text-[var(--muted)]">Summary generated by {modelUsed}</p>
      )}
    </div>
  );
}
